#!/usr/bin/python3

import sys

def main():
    args = sys.argv[1:]
    if len(args) != 2:
        print("Usage: add2 <x> <y>")
        sys.exit(1)
    x, y = args
    sum = int(x) + int(y)
    print(f"Sum of {x} + {y}: {sum}")
    
if __name__ == "__main__":
    main()
